import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { DM_Sans, Anton } from "next/font/google"

const dmSans = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--DMSans",
  subsets: ["latin"],
  preload: true
})

const anton = Anton({
  weight: ["400"],
  variable: "--Anton",
  subsets: ["latin"],
  preload: true
})

export const metadata = {
  title: "XHIL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${anton.variable} font-DM_Sans bg-background text-white`}>

        <div className="flex flex-col w-full min-h-screen">

          {/* Navbar */}
          <Navbar />

          <div className="flex-1">
            {children}
          </div>

          {/* Footer */}
          <Footer />

        </div>

      </body>
    </html>
  );
}
